name: canteen_food_ordering_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # This range allows Dart SDK 3.x

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  fluttertoast: ^8.2.2
  uuid: ^4.5.1
  path: ^1.8.3
  progress_dialog_null_safe:   # Use this or replace with flutter_easyloading
  curved_navigation_bar: ^1.0.1
  razorpay_flutter: ^1.3.4
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  permission_handler: ^11.3.1

  cloudinary: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
