// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Cg69u-OizXO3zgafLUTHu4k1ICOsL5I',
    appId: '1:131659268023:android:60b8498eeaab587952b232',
    messagingSenderId: '131659268023',
    projectId: 'universitycanteen-505e5',
    storageBucket: 'universitycanteen-505e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqFuLd6B8oXeeV2FaAHPgmAIDAIg1VDQI',
    appId: '1:131659268023:ios:cb06ca976a8777d952b232',
    messagingSenderId: '131659268023',
    projectId: 'universitycanteen-505e5',
    storageBucket: 'universitycanteen-505e5.firebasestorage.app',
    iosBundleId: 'com.example.canteenFoodOrderingApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCWHp-BiC0HdYsYMq1-oVUWASQsOimQ6s',
    appId: '1:131659268023:web:7c299ea1ac19c24452b232',
    messagingSenderId: '131659268023',
    projectId: 'universitycanteen-505e5',
    authDomain: 'universitycanteen-505e5.firebaseapp.com',
    storageBucket: 'universitycanteen-505e5.firebasestorage.app',
  );

}